import os
from pathlib import Path

# Base Paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_PATH = DATA_DIR / "raw" / "twcs_full.parquet"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
GOLDEN_DATA_DIR = DATA_DIR / "golden"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"

# Target Brand
TARGET_BRAND = "AmazonHelp"

# Final 8-Intent Taxonomy
INTENTS = [
    "DELIVERY_STATUS_DELAY",
    "DAMAGED_WRONG_MISSING",
    "REFUND_RETURN_EXCHANGE",
    "ORDER_CHANGE_CANCEL",
    "BILLING_SUBSCRIPTION_PRIME",
    "ACCOUNT_SECURITY_ACCESS",
    "TECHNICAL_PRODUCT_SUPPORT",
    "FEEDBACK_COMPLAINT_GENERAL",
]

# Priority Hierarchy for Multi-Intent Collisions
INTENT_PRIORITY = [
    "ACCOUNT_SECURITY_ACCESS",
    "DAMAGED_WRONG_MISSING",
    "BILLING_SUBSCRIPTION_PRIME",
    "REFUND_RETURN_EXCHANGE",
    "ORDER_CHANGE_CANCEL",
    "DELIVERY_STATUS_DELAY",
    "TECHNICAL_PRODUCT_SUPPORT",
    "FEEDBACK_COMPLAINT_GENERAL",
]

# Triage Action Definitions
DECISION_AUTO_HANDLE = "AUTO_HANDLE"
DECISION_ESCALATE = "ESCALATE"

# Escalation Categories
ESCALATION_CATEGORIES = [
    "NONE",
    "ACCOUNT_SECURITY_RISK",
    "LOST_OR_STOLEN_DELIVERY",
    "DAMAGED_PHYSICAL_MERCHANDISE",
    "FINANCIAL_OR_BILLING_DISPUTE",
    "MANUAL_REFUND_OR_RETURN_OVERRIDE",
    "CUSTOMER_AGITATION_OR_LEGAL_THREAT",
    "ACCOUNT_SPECIFIC_PII_REQUIRED",
    "AMBIGUOUS_INQUIRY_NEEDS_CLARIFICATION"
]

# Seed for reproducibility
RANDOM_SEED = 42
